# Generated by Django 4.2.3 on 2023-07-26 15:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weathervalue',
            name='city_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='weathervalue',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 26, 18, 55, 45, 282080)),
        ),
    ]
