# Generated by Django 4.2.3 on 2023-08-15 09:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weathervalue',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 15, 12, 12, 20, 690890)),
        ),
    ]
