# Generated by Django 4.2.3 on 2023-08-15 10:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_alter_weathervalue_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weathervalue',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 15, 13, 37, 54, 525229)),
        ),
    ]
