# Generated by Django 4.2.3 on 2023-07-26 16:33

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_weathervalue_city_id_alter_weathervalue_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weathervalue',
            name='city_id',
        ),
        migrations.AddField(
            model_name='weathervalue',
            name='cities',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='weather.city'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='weathervalue',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 26, 19, 33, 32, 913115)),
        ),
    ]
