# Generated by Django 4.2.3 on 2023-07-29 23:49

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0001_initial'),
        ('weather', '0003_remove_weathervalue_city_id_weathervalue_cities_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weathervalue',
            name='cities',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cities.city'),
        ),
        migrations.AlterField(
            model_name='weathervalue',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 30, 2, 49, 17, 574)),
        ),
        migrations.AlterModelTable(
            name='weathervalue',
            table='cities_weathervalue',
        ),
        migrations.DeleteModel(
            name='city',
        ),
    ]
